# Generated by Django 4.2.29 on 2026-09-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clothing', 'Одежда'), ('navigation', 'Навигация'), ('food', 'Еда и вода'), ('safety', 'Безопасность'), ('camping', 'Ночёвка')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('essential', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(default='Заилийский Алатау', max_length=160)),
                ('altitude', models.PositiveIntegerField(help_text='Высота над уровнем моря в метрах')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('moderate', 'Средний'), ('hard', 'Сложный')], default='moderate', max_length=12)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=5, max_digits=4)),
                ('distance_km', models.DecimalField(decimal_places=1, default=8, max_digits=5)),
                ('best_season', models.CharField(default='Июнь — сентябрь', max_length=120)),
                ('short_description', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('safety_notes', models.TextField(default='Проверьте погоду и сообщите близким о маршруте.')),
                ('image_url', models.URLField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_featured', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SavedHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_hikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GearCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_it', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedhike',
            constraint=models.UniqueConstraint(fields=('user', 'mountain'), name='unique_user_saved_mountain'),
        ),
        migrations.AddConstraint(
            model_name='gearcheck',
            constraint=models.UniqueConstraint(fields=('user', 'equipment'), name='unique_user_equipment_check'),
        ),
    ]
