# Generated by Django 5.2.17 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='latitude',
            field=models.FloatField(default=43.15),
        ),
        migrations.AddField(
            model_name='mountain',
            name='longitude',
            field=models.FloatField(default=77.05),
        ),
    ]
